[package]
name = "ascii_robot"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.11"
wgpu = "25.0.2"
pollster = "0.4.0"
gilrs = "0.11.0"
nokhwa = { version = "0.10", features = ["input-msmf", "input-v4l", "input-avfoundation"] }
image = "0.25.6"

